# numpy: Introduction

Let's import the `numpy` module.

In [2]:
import numpy as np

In [4]:
n = 10  # CHANGE ME
a1 = list(range(n))
a2 = np.arange(n)

if n <= 10:
    print(a1)
    print(a2)
type(a2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [7]:
%timeit [i**2 for i in a1]

The slowest run took 4.32 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.38 µs per loop


In [8]:
%timeit a2**2

The slowest run took 10.39 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.63 µs per loop


Numpy Arrays: much less flexible, but:

* much faster
* less memory

---

Ways to create a numpy array:

* Casting from a list

In [5]:
np.array([1,2,3])

array([1, 2, 3])

* `linspace`

In [13]:
np.linspace(-1, 1,10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

* `zeros`

In [7]:
np.zeros((10,10), np.float64)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

---

Operations on arrays propagate to all elements:

In [14]:

a = np.array([1.2, 3, 4])
b = np.array([0.5, 0, 1])

Addition, multiplication, power, .. are all elementwise:

In [15]:
a+b

array([ 1.7,  3. ,  5. ])

In [16]:
a*b

array([ 0.6,  0. ,  4. ])

In [17]:
a**b

array([ 1.09544512,  1.        ,  4.        ])

Matrix multiplication is `np.dot(A, B)` for two 2D arrays.

---

Numpy arrays have two (most) important attributes:

In [22]:
a = np.random.rand(5, 4, 3)
a.shape
print a

[[[ 0.50753517  0.33236307  0.50913407]
  [ 0.71958726  0.70142331  0.00385294]
  [ 0.9505202   0.28799638  0.03699909]
  [ 0.32372927  0.96923246  0.56467026]]

 [[ 0.34937251  0.19569208  0.45413779]
  [ 0.52220885  0.41192632  0.16460157]
  [ 0.23829641  0.91224007  0.68512547]
  [ 0.8804097   0.34280195  0.16378588]]

 [[ 0.08145883  0.8320769   0.5744545 ]
  [ 0.36204294  0.76906319  0.26363928]
  [ 0.37790062  0.94551033  0.36669813]
  [ 0.59955552  0.59276891  0.33387776]]

 [[ 0.94895819  0.31654582  0.15984505]
  [ 0.91277004  0.38594414  0.62214554]
  [ 0.57214554  0.74415487  0.00660748]
  [ 0.99102434  0.83102609  0.76134033]]

 [[ 0.4766153   0.44454164  0.48167591]
  [ 0.23611436  0.97784055  0.96070601]
  [ 0.74489578  0.11902218  0.87341088]
  [ 0.44598953  0.20128606  0.8410367 ]]]


In [14]:
a.dtype

dtype('float64')

Other `dtype`s include `np.complex64`, `np.int32`, ...