# numpy: Indexing

In [1]:
import numpy as np

In [4]:
a = np.random.rand(3,4,5)
a.shape
print a

[[[ 0.65452046  0.84655751  0.2465437   0.63037249  0.49431094]
  [ 0.63158188  0.78362859  0.2951747   0.69641117  0.59895715]
  [ 0.43613357  0.87651063  0.38305138  0.00624028  0.03163046]
  [ 0.91546204  0.70171905  0.547058    0.72028989  0.84687566]]

 [[ 0.87033005  0.20760023  0.25703377  0.10136388  0.87121432]
  [ 0.77882111  0.06744337  0.64009465  0.16001312  0.57535136]
  [ 0.53609744  0.68586251  0.50275466  0.90559502  0.0291146 ]
  [ 0.1564075   0.77657475  0.59519404  0.50203518  0.29774104]]

 [[ 0.10071063  0.02232977  0.91270321  0.87303005  0.07230418]
  [ 0.40382633  0.70463072  0.97308786  0.43831008  0.73621499]
  [ 0.27980156  0.28648138  0.14066115  0.04852876  0.96052156]
  [ 0.64120322  0.02888591  0.51249984  0.70559775  0.93863945]]]


What's the result of this?
a[...,1] display based on col
a[:1] dispaly based on row

In [10]:
print a[...,1]

[[ 0.84655751  0.78362859  0.87651063  0.70171905]
 [ 0.20760023  0.06744337  0.68586251  0.77657475]
 [ 0.02232977  0.70463072  0.28648138  0.02888591]]


In [3]:
a[0].shape

(4, 5)

And this?

In [4]:
print a
print a[...,2]
a[...,2].shape

[[[ 0.20036881  0.65911349  0.55520155  0.51080554  0.81495794]
  [ 0.5759689   0.64804231  0.78066361  0.85494734  0.67881983]
  [ 0.09244949  0.13435257  0.9967763   0.01953128  0.18814341]
  [ 0.36142812  0.72967266  0.5456059   0.31794577  0.17642136]]

 [[ 0.23519178  0.76973923  0.46971127  0.20148297  0.73445054]
  [ 0.45462708  0.9766486   0.39990995  0.58228592  0.1012433 ]
  [ 0.13646585  0.42436945  0.63316949  0.21844417  0.66665099]
  [ 0.96002238  0.45663891  0.87922002  0.46085103  0.06232283]]

 [[ 0.23227256  0.49036587  0.26758193  0.83680638  0.01062927]
  [ 0.10093378  0.98836619  0.2952474   0.80749719  0.34966229]
  [ 0.47070504  0.94045287  0.88796667  0.86516448  0.76537614]
  [ 0.76026903  0.15113926  0.16647953  0.68203895  0.44708797]]]
[[ 0.55520155  0.78066361  0.9967763   0.5456059 ]
 [ 0.46971127  0.39990995  0.63316949  0.87922002]
 [ 0.26758193  0.2952474   0.88796667  0.16647953]]


(3, 4)

In [5]:
a[1,0,3]

0.025588609438720655

Like all other things in Python, numpy indexes from 0.

In [6]:
a[3,2,2].shape

IndexError: index 3 is out of bounds for axis 0 with size 3

In [6]:
a[:,2].shape

(3, 5)

---

Indexing into numpy arrays usually results in a so-called *view*.

In [8]:
a = np.zeros((4,4))
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

Let's call `b` the top-left $2\times 2$ submatrix.

In [9]:
b = a[:2,:2]
b

array([[ 0.,  0.],
       [ 0.,  0.]])

What happens if we change `b`?

In [10]:
b[1,0] = 5
b

array([[ 0.,  0.],
       [ 5.,  0.]])

In [12]:
print(a)

[[ 0.  0.  0.  0.]
 [ 5.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


To decouple `b` from `a`, use `.copy()`.

In [13]:
b = b.copy()
b[1,1] = 7
print(a) 

[[ 0.  0.  0.  0.]
 [ 5.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


----

You can also index with other arrays:

In [14]:
a = np.random.rand(4,4)
a

array([[ 0.94747406,  0.89080192,  0.46799144,  0.54340544],
       [ 0.54409333,  0.27586608,  0.60682897,  0.61962813],
       [ 0.06203009,  0.7958913 ,  0.93468584,  0.88864481],
       [ 0.98627827,  0.73442815,  0.90304704,  0.18186312]])

In [15]:
i = np.array([0,2])
a[i]

array([[ 0.94747406,  0.89080192,  0.46799144,  0.54340544],
       [ 0.06203009,  0.7958913 ,  0.93468584,  0.88864481]])

---

And with conditionals:

In [16]:
a>0.5

array([[ True,  True, False,  True],
       [ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]], dtype=bool)

In [17]:
a[a>0.5]

array([ 0.94747406,  0.89080192,  0.54340544,  0.54409333,  0.60682897,
        0.61962813,  0.7958913 ,  0.93468584,  0.88864481,  0.98627827,
        0.73442815,  0.90304704])